import { MenuItem, RestaurantSettings } from './types';

export const INITIAL_SETTINGS: RestaurantSettings = {
  name: 'مطعم باب شرقي',
  phone: '065005050',
  address: 'عمان، الشارع الرئيسي - مقابل البوابة الشرقية',
  deliveryFee: 1.5,
  currency: 'د.أ',
  isOpen: true,
};

export const DEFAULT_MENU_ITEMS: MenuItem[] = [
  {
    id: 'sh-1',
    name: 'شاورما دبل باب شرقي',
    description: 'وجبتنا المميزة! قطعتين شاورما دجاج محشوة بالثوم البطاطس المقرمشة، مدهونة بدبس الرمان والزيت على الفحم، تقدم مع المخلل والثومية والبطاطس المقرمشة.',
    price: 3.75,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1642970347854-c9f280a5682b?auto=format&fit=crop&w=800&q=80',
    available: true,
    add_on_options: ['جبن زيادة', 'ثوم إضافي', 'صلصة حارة', 'بطاطا زيادة'],
  },
  {
    id: 'sh-2',
    name: 'سوبر شاورما عربي فرط',
    description: 'صحن شاورما دجاج شرائح مقطعة وتقدم مع كمية مضاعفة من الثومية المميزة لدينا، مع بطاطا مقلية عائلية، مخلل بلدي، وقطع من خبز الصاج الطازج.',
    price: 4.50,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    available: true,
    add_on_options: ['طحينية', 'مخلل زيادة', 'ثوم حار'],
  },
  {
    id: 'sh-3',
    name: 'ساندويش شاورما سوبر شروق',
    description: 'ساندويش شاورما كبير بخبز الشروق الرقيق الغني بالثوم ودبس الرمان والمخلل المقرمش، محضر ومحمص على الجريل باحترافية عالية.',
    price: 2.25,
    category: 'shawarma',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    available: true,
    add_on_options: ['ثوم دبل', 'سبايسي حار'],
  },
  {
    id: 'br-1',
    name: 'بروستد سوبر كريسبي (4 قطع)',
    description: '4 قطع من أفضل الدجاج الطازج المغطى بتتبيلة باب شرقي السرية والمقلي ليكون كرانشي ومقرمش من الخارج وطري ولذيذ من الداخل، يقدم مع بطاطا، ثومية، خبز، وكولسلو.',
    price: 5.50,
    category: 'broasted',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80',
    available: true,
    add_on_options: ['حار سبايسي', 'ثوم زيادة', 'كولسلو إضافي'],
  },
  {
    id: 'br-2',
    name: 'وجبة البروستد العائلية (8 قطع)',
    description: '8 قطع دجاج مقرمش ذهبي بتتبيلتنا الغنية، مغلفة بطبقة كرانشي خفيفة، تقدم مع علبتين بطاطس عائلية، ثوميتين كبيرتين، سلطة كولسلو عائلية، وخبز طازج.',
    price: 10.00,
    category: 'broasted',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
    available: true,
    add_on_options: ['قطع حار وقطع عادي', 'لتر كولا عائلي'],
  },
  {
    id: 'ap-1',
    name: 'حمص بيروتي بالزيت والمكسرات',
    description: 'طبق حمص بلدي طازج مخفوق بالطحينة وعصير الليمون، مزين بالبقدونس، زيت الزيتون البكر، وحبات الصنوبر والمكسرات المحمصة.',
    price: 1.75,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1547058881-aa0edd92aab3?auto=format&fit=crop&w=800&q=80',
    available: true,
    add_on_options: ['خبز إضافي', 'قرن فلفل حار'],
  },
  {
    id: 'ap-2',
    name: 'كبة شامية مقلية (4 حبات)',
    description: 'أربع أقراص كبة محشوة باللحم البلدي المفروم والمطبوخ مع البصل ودبس الرمان والبهارات الشامية العريقة مضافاً إليها اللوز المحمص.',
    price: 2.25,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80',
    available: true,
    add_on_options: [],
  },
  {
    id: 'ap-3',
    name: 'صحن متبل باذنجان مشوي',
    description: 'باذنجان مشوي على اللهب مهروث ومخلوط بالطحينة الغنية والثوم وعصير الليمون الطازج، مزين بحبات الرمان اللامعة وزيت الزيتون الشامي.',
    price: 1.50,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'dr-1',
    name: 'كوكتيل إمبراطور باب شرقي',
    description: 'عصير فواكه طبيعية طبقات طازجة من المانجو، الفراولة، الموز والحليب، مغطى بطبقة غنية من القشطة البلدية والبلد ومزينة بالعسل والمكسرات.',
    price: 2.00,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
    available: true,
  },
  {
    id: 'dr-2',
    name: 'مشروبات غازية متنوعة',
    description: 'علبة باردة ومنعشة من اختيارك (بيبسي، سفن أب، دايت، كوكاكولا، فانتا).',
    price: 0.60,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
    available: true,
  }
];
